### ISSUE TITLE
Lovely theme! I think there's a small fix needed...?

### ISSUE THREAD

**Issue by lirantal** [moudev/slidev-theme-purplin#10]
Hi friend, lovely work on this theme!

I think there's a small issue with the [example.md](https://github.com/moudev/slidev-theme-purplin/blob/main/example.md) file. It currently sets `theme: none` but it should actually have `theme: purplin`, right?

Happy to send in a PR in case I didn't miss anything about that.

**Comment by moudev** [comment]
Thanks, @lirantal!
Sure, please send the PR, and thanks for the observation.
