### ISSUE TITLE
[BUG] Missing styles in latest version

### ISSUE THREAD

**Issue by EmaSuriano** [moudev/slidev-theme-purplin#12]
Hello @moudev,

I followed the steps to install the theme, and it looks like there is a mismatch between the [Demo](https://slidev-theme-purplin.netlify.app/1) in the repository and a fresh setup of the theme.

I created a [Stackblitz](https://stackblitz.com/edit/slidev-3s8vc3?file=slides.md) to demo how it's working using the `latest` version of the theme, and also the same `slide.md` from the repository.

Here are some screenshots that highlights the differences:

| Main | Image | Quote | 
| --- | --- | --- | 
| <img width="1788" alt="image" src="https://user-images.githubusercontent.com/3399429/200770345-99f39ed1-9332-4bb4-b786-d24df146f906.png"> | <img width="1788" alt="image" src="https://user-images.githubusercontent.com/3399429/200770375-106ce1fc-ec1e-4df5-b12e-a299207c983b.png"> | <img width="1788" alt="image" src="https://user-images.githubusercontent.com/3399429/200770398-ee234505-67d2-4b74-9e1e-6521a2170e50.png"> |

I checked the Terminal and I found many Vue warning when applying styles. It's clear that the issue is there: 

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/3399429/200769881-f514d476-aee0-4ff4-b0f5-46ccf9356343.png">

## Final Note

I cloned the repository and run the demo code, to actually see the differences between a fresh install and the example. I can see the styles properly and there are no warning in the Terminal.

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/3399429/200770272-195ef9ac-d9e6-4fbc-8e2a-904afa688421.png">

The theme looks quite promising, and I would like to use it as it looks in the demo. Thanks for sharing it!

**Comment by IanVS** [comment]
I'm seeing the same thing.  Looks like a great theme, but out-of-the-box it appears to be broken.

**Comment by moudev** [comment]
Hi, I updated the slidev version. The [v1.2.0](https://github.com/moudev/slidev-theme-purplin/releases/tag/v1.2.0) of the theme has been published.

The problem was the `setup()` used in the components that receive props. I solved it using [`theme-apple-basic`](https://github.com/slidevjs/themes/blob/main/packages/theme-apple-basic/layouts/intro-image.vue) layout as example.

Sorry for the delay and thanks for had published the issue. I appreciate your interest in using the theme.
